version: '3'

volumes:
  pg_data_production_fdgrm:
  static_volume_fdgrm:
  media_volume_fdgrm:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production_fdgrm:/var/lib/postgresql/data

  backend:
    image: daryakefir/foodgram_backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume_fdgrm:/backend_static
      - media_volume_fdgrm:/app/media

  frontend:
    image: daryakefir/foodgram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume_fdgrm:/frontend_static
    depends_on:
      - backend

  gateway:
    image: daryakefir/foodgram_gateway:latest
    env_file: .env
    depends_on:
      - frontend
    volumes:
      - static_volume_fdgrm:/staticfiles/
      - media_volume_fdgrm:/app/media
    ports:
      - 8000:80
