# Generated by Django 3.2.3 on 2024-10-02 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_ingredientsamountinrecipe_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsamountinrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_in_recipe', to='recipes.recipe'),
        ),
    ]
