# Generated by Django 3.2.3 on 2024-10-11 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_auto_20241007_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsamountinrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество ингредиентов:1'), django.core.validators.MaxValueValidator(32000, message='Максимальное количество ингредиентов:32000')]),
        ),
    ]
