# Generated by Django 3.2.3 on 2024-10-04 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username должен содержать только буквы и цифры.', regex='^[a-zA-Z0-9]*$')]),
        ),
    ]
