# Generated by Django 3.2.3 on 2024-10-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20241007_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_related_name': 'users', 'ordering': ('id',), 'verbose_name': 'Пользователи'},
        ),
    ]
