# Generated by Django 3.2.3 on 2024-09-29 17:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_delete_follow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase',
            new_name='Shopping_cart',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
