# Generated by Django 3.2.3 on 2024-09-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20240929_1733'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='unique_recipe_ingredient',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='recipes.Tag'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('ingredients', 'recipe'), name='unique_recipe_ingredient'),
        ),
    ]
