# Generated by Django 3.2.3 on 2024-10-02 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_recipeingredient_ingredientsamountinrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsamountinrecipe',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество ингредиентов:0.01')]),
        ),
    ]
