# Generated by Django 3.2.3 on 2024-10-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20241005_1611'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientsamountinrecipe',
            constraint=models.UniqueConstraint(fields=('ingredients', 'recipe'), name='unique_recipe_ingredient'),
        ),
    ]
